---
apiVersion: podmortem.redhat.com/v1alpha1
kind: PatternLibrary
metadata:
  name: quarkus-patterns
  namespace: podmortem-system
  labels:
    pattern-type: "quarkus"
    environment: "production"
spec:
  repositories:
    - name: "quarkus-patterns-repo"
      url: "https://github.com/your-org/patterns-quarkus.git"
      branch: "main"
      # Optional credentials for private repositories
      # credentials:
      #   secretRef: "git-secret"
  
  refreshInterval: "1h"
  
  # Enable patterns from the simplified structure
  enabledLibraries:
    # Core framework patterns (startup, CDI, config, dev mode, native, etc.)
    - "quarkus-core-patterns"
    
    # Extension patterns (separated by type)
    - "quarkus-data-extensions"        # Database, JPA, Panache, transactions
    - "quarkus-messaging-extensions"   # Kafka, reactive messaging, streams
    - "quarkus-rest-extensions"        # REST client, gRPC, OpenAPI, JSON
    - "quarkus-other-extensions"       # Caching, scheduling, async, Vert.x
    
    # Security patterns
    - "quarkus-security-patterns"      # Authentication, JWT, OAuth2, RBAC
    
    # Cloud-native patterns  
    - "quarkus-cloud-native-patterns"  # Health, metrics, K8s, tracing

status:
  lastSyncTime: "2024-01-15T10:00:00Z"
  availableLibraries:
    - libraryId: "quarkus-core-patterns"
      version: "1.0.0"
      patternCount: 9
      categories: ["application_framework", "dependency_injection", "configuration", "development", "native_compilation", "build"]
      status: "Ready"
      
    - libraryId: "quarkus-data-extensions"
      version: "1.0.0"
      patternCount: 4
      categories: ["data_access", "database", "persistence", "orm"]
      status: "Ready"
      
    - libraryId: "quarkus-messaging-extensions"
      version: "1.0.0"
      patternCount: 5
      categories: ["messaging", "reactive", "event_streaming", "async_processing"]
      status: "Ready"
      
    - libraryId: "quarkus-rest-extensions"
      version: "1.0.0"
      patternCount: 6
      categories: ["rest_client", "grpc", "communication", "api_documentation"]
      status: "Ready"
      
    - libraryId: "quarkus-other-extensions"
      version: "1.0.0"
      patternCount: 6
      categories: ["caching", "scheduling", "background_tasks", "async_processing"]
      status: "Ready"
      
    - libraryId: "quarkus-security-patterns"
      version: "1.0.0"
      patternCount: 5
      categories: ["security", "authentication", "authorization", "jwt", "oauth"]
      status: "Ready"
      
    - libraryId: "quarkus-cloud-native-patterns"
      version: "1.0.0"
      patternCount: 6
      categories: ["cloud_native", "observability", "monitoring", "health_checks", "kubernetes", "tracing"]
      status: "Ready"
      
  syncStatus: "Successful"
  message: "Pattern libraries loaded successfully with simplified structure"

---
# Development environment configuration
apiVersion: podmortem.redhat.com/v1alpha1
kind: PatternLibrary
metadata:
  name: quarkus-dev-patterns
  namespace: podmortem-dev
  labels:
    pattern-type: "quarkus"
    environment: "development"
spec:
  repositories:
    - name: "quarkus-patterns-repo"
      url: "https://github.com/your-org/patterns-quarkus.git"
      branch: "develop"  # Use development branch
  
  refreshInterval: "15m"  # More frequent updates for dev
  
  enabledLibraries:
    # Focus on core and development-related patterns
    - "quarkus-core-patterns"           # Includes dev mode hot reload
    - "quarkus-data-extensions"         # Database issues common in dev
    - "quarkus-rest-extensions"         # API development patterns

---
# Minimal configuration for specific use cases
apiVersion: podmortem.redhat.com/v1alpha1
kind: PatternLibrary
metadata:
  name: quarkus-minimal-patterns
  namespace: podmortem-system
  labels:
    pattern-type: "quarkus"
    environment: "minimal"
spec:
  repositories:
    - name: "quarkus-patterns-repo"
      url: "https://github.com/your-org/patterns-quarkus.git"
      branch: "main"
  
  refreshInterval: "2h"
  
  enabledLibraries:
    # Just core and most critical patterns
    - "quarkus-core-patterns"
    - "quarkus-data-extensions"
    - "quarkus-security-patterns"

---
# Enterprise configuration with custom patterns
apiVersion: podmortem.redhat.com/v1alpha1
kind: PatternLibrary
metadata:
  name: quarkus-enterprise-patterns
  namespace: podmortem-system
  labels:
    pattern-type: "quarkus"
    environment: "enterprise"
spec:
  repositories:
    # Public community patterns
    - name: "quarkus-community-patterns"
      url: "https://github.com/podmortem/patterns-quarkus.git"
      branch: "main"
    
    # Private enterprise patterns
    - name: "enterprise-quarkus-patterns"
      url: "https://github.com/yourcompany/private-quarkus-patterns.git"
      branch: "main"
      credentials:
        secretRef: "enterprise-git-secret"
  
  refreshInterval: "30m"
  
  enabledLibraries:
    # All community patterns
    - "quarkus-core-patterns"
    - "quarkus-data-extensions"
    - "quarkus-messaging-extensions"
    - "quarkus-rest-extensions"
    - "quarkus-other-extensions"
    - "quarkus-security-patterns"
    - "quarkus-cloud-native-patterns"
    
    # Enterprise-specific patterns (from private repo)
    - "enterprise-quarkus-security"      # Custom security patterns
    - "enterprise-quarkus-compliance"    # Compliance and audit patterns
    - "enterprise-quarkus-integration"   # Internal system integration patterns 